version: '3'
services:
  db:
    image: mysql
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./var/run/mysqld/mysqld.sock
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db